import { CAPABILITIES } from "./capabilities";

export const ROLE_CAPABILITIES: Record<string, string[]> = {
  ADMIN: ["*"],

  ENGINEER: [
    CAPABILITIES.AI_COMMAND_EXECUTE,
    CAPABILITIES.AI_COMMAND_QUERY,
    CAPABILITIES.DATA_EXPORT_PDF,
    CAPABILITIES.DATA_EXPORT_SNAPSHOT,
    CAPABILITIES.INFRA_PROVISION,
  ],

  OPERATOR: [CAPABILITIES.AI_COMMAND_QUERY, CAPABILITIES.EMERGENCY_STOP_LOCAL],

  AUDITOR: [CAPABILITIES.DATA_EXPORT_PDF],
};
